title: Vippy
description: A customizable portfolio template for virtual photography
url: https://your-site.com
baseurl: ''
remote_theme: YoussefRaafatNasry/portfolYOU
logo: /assets/logo.png
keywords: portfolio, photography, developer, personal site
plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
nav_exclude:
  - pages/tags.html
  - pages/404.html
  - pages/index.md
author:
  name: Vippy
permalink: /:categories/:title
collections:
  projects:
    output: true
    permalink: /projects/:name
virtual_photography:
  show_date: true
  show_tags: true
analytics:
  enabled: true
  google:
    tracking_id: ''
defaults:
  - scope:
      path: ''
      type: projects
    values:
      layout: page
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
      comments: false
sass:
  style: compressed
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - '*.log'
  - admin/
  - vippy-admin/
  - REFERENCE/
  - .b2-config.json
site_modules:
  - id: virtual_photography
    name: Virtual Photography
    url: /virtual-photography/
    enabled: true
    icon: bi-camera
    admin_url: /vippy/vp
  - id: projects
    name: Projects
    url: /projects/
    enabled: true
    icon: bi-code-square
    admin_url: /vippy/projects
  - id: blog
    name: Blog
    url: /blog/
    enabled: true
    icon: bi-journal-text
    admin_url: /vippy/blog
  - id: about
    name: About
    url: /about/
    enabled: true
    icon: bi-person-circle
    admin_url: /vippy/about
